sudo: required
services:
  - docker

before_install:
  - docker build -t andreas100/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true andreas100/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-285616724900"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



